#ifndef TYPES_H
#define TYPES_H

/* This file isn't really necessary for OpenWatcom projects, but I use the
   code in Turbo C projects so... yeah. */

/* Generic types */

typedef unsigned char  u8;
typedef unsigned short u16;
typedef unsigned long  u32;
typedef signed   char  i8;
typedef signed   short i16;
typedef signed   long  i32;

typedef u8             bool;

#define true  ((u8) 1)
#define false ((u8) 0)

/* Application specific types */

#endif
